version: '2.17.2'
services:
  front:
    build:
      context: .
      dockerfile: ./upload/Dockerfile
      
    ports:
      - '0.0.0.0:5173:5173'

  back:
    build:
      context: .
      dockerfile: ./back/Dockerfile
      
    ports:
      - '5000:5000'